backend:
  - any: ['backend/**/*']

frontend:
  - any: ['frontend/**/*']

ci:
  - any: ['.github/**/*']

docker:
  - any: ['**/Dockerfile', 'docker-compose.yml']

docs:
  - any: ['docs/**/*', 'README.md', 'CONTRIBUTING.md']

scripts:
  - any: ['scripts/**/*']

