repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0  # use latest version
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.9
    hooks:
      - id: prettier
        files: ^frontend/
        args: [--check]
        additional_dependencies:
          - prettier@3.4.2